services:
  web:
    image: php_apache_sde2
    container_name: apache_server
    ports:
      - 80:80
    volumes:
      - D:/trabajo/ib/sde:/var/www/html
    depends_on:
      - db
 
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: galegria
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - 5432:5432
