version: "3.9"

services:
    web:
        container_name: ${COMPOSE_PROJECT_NAME:-sde}_web
        build:
            context: .
            dockerfile: .docker/Dockerfile
        ports:
            - "${WEB_PORT:-80}:80"
        volumes:
            # Montar el código completo del proyecto en DocumentRoot
            - ${LOCAL_SRC_PATH:-.}:/var/www/html

            # Asegurarse que el .htaccess no se sobrescriba (opcional, solo si está en un lugar diferente)
            # - ./.htaccess:/var/www/html/.htaccess:ro

            # Configuración de PHP personalizada
            - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro

            # Evitar sobrescribir logs y cache
            - /var/www/html/application/logs
            - /var/www/html/application/cache
        environment:
            - CI_ENV=${CI_ENV:-development}
            - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-256M}
            - PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-300}
            - APACHE_DOCUMENT_ROOT=/var/www/html
        depends_on:
            - db
        restart: unless-stopped
        networks:
            - app-network

    db:
        container_name: ${COMPOSE_PROJECT_NAME:-sde}_db
        build:
            context: .
            dockerfile: .docker/PSQL.Dockerfile
        ports:
            - "${DB_PORT:-5432}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${DB_USER:-username}
            - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
            - POSTGRES_DB=${DB_NAME:-testdb}
        restart: unless-stopped
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
        driver: local
